name: "order-mgr: Deploy to GCP"

on:
  push:
    branches:
      - main
    paths:
      - 'order-mgr/**'

defaults:
  run:
    shell: bash
    working-directory: order-mgr

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Set up auth
        uses: google-github-actions/auth@c4799db9111fba4461e9f9da8732e5057b394f72 # v0.8.3
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@ee9693ff89cdf73862b8a13988f6a71070e8fc58 # v0.6.2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: "Export environment variables to yaml file"
        env:
          SQUARE_ENVIRONMENT: production
          EVENT_DATE: "2022-04-01"
        run: |
          echo "SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}" > .env.yaml
          echo "SQUARE_ENVIRONMENT: ${SQUARE_ENVIRONMENT}" >> .env.yaml
          echo "SQUARE_LOCATION: ${{ secrets.SQUARE_LOCATION }}" >> .env.yaml
          echo "EVENT_DATE: ${EVENT_DATE}" >> .env.yaml

      - name: "Create square.order.created topic for pubsub"
        # if topic already exists this call will fail but that is OK
        continue-on-error: true
        run: |
          gcloud pubsub topics create projects/${{ secrets.GCLOUD_PROJECT_ID }}/topics/square.order.created
      - name: "Deploy order-mgr-created function with a PubSub trigger"
        run: |
          gcloud functions deploy order-mgr-created --entry-point handle_created --env-vars-file .env.yaml --runtime python39 --trigger-topic=projects/${{ secrets.GCLOUD_PROJECT_ID }}/topics/square.order.created --memory=128MB
      - name: "Create square.order.updated topic for pubsub"
        # if topic already exists this call will fail but that is OK
        continue-on-error: true
        run: |
          gcloud pubsub topics create projects/${{ secrets.GCLOUD_PROJECT_ID }}/topics/square.order.updated
      - name: "Deploy order-mgr-updated function with a PubSub trigger"
        run: |
          gcloud functions deploy order-mgr-updated --entry-point handle_updated --env-vars-file .env.yaml --runtime python39 --trigger-topic=projects/${{ secrets.GCLOUD_PROJECT_ID }}/topics/square.order.updated --memory=128MB
